image: node:latest
variable:
  script:
    - echo $YUQUE_TOKEN
    - echo $ALGOLIA_ADMIN_API_KEY
pages:
  script:
    - npm install
    - git clone -b json https://github.com/ccknbc-actions/blog-butterfly.git json
    - mv -f ./json/yuque.json ./
    - npm run gitlab-yuque
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
