image: node:latest
variable:
  script:
    - echo $YUQUE_TOKEN
    - echo $ALGOLIA_ADMIN_API_KEY
pages:
  script:
    - yarn hexo-cli
    - test -e package.json && yarn install
    - yarn start
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
