pull_request_rules:
- name: automatic merge if author is renovate[bot]
  conditions:
    - author=renovate[bot]
  actions:
    merge:
      method: merge

- name: automatic merge if author is github-actions[bot]
  conditions:
    - author=github-actions[bot]
  actions:
    merge:
      method: merge