# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# webPushNotification:
#   webpushrKey: "UIngQiMfLAHGhZ-LkzRFKtvHh9CqUYnY3yipDB2qPB0"
#   webpushrAuthToken: "7953"
#   trackingCode: "BDMQzEpmBuoEMOFVQ5EiC7scntMuJzY5Ac2rYD9NPSxPXqZ_VpC8Xk_iuuW0s6M7jioHyy05qzqyD28i4ikaThw"

# Site
title: CC康纳百川
subtitle: 'Hello Word'
description: '一个无趣的人'
keywords: CC的部落格
author: CC康纳百川
# 需修改Hexo默认的空值为确切的语言列表，记得在主题languages目录下添加对应的语言.yml文件
language: zh-CN
timezone: 'Asia/Shanghai'


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ccknbc.github.io/

# abbrlink config
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: dec        #support dec(default) and hex
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true  #true(default)
     depth:        #3(default)
     over_write: false 
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: true #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink.


root: /
permalink: posts/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :language
skip_render:
  - 404.html
  - README.md
  - robots.txt
  - CNAME
  - lete.html
  - google7787a6577761be93.html
  # - baidu_verify_W5KnhGrIiJ.html
  # - baidu_verify_iDHY27SKF7.html
  # - baidu_verify_VmoU6BLPQt.html
  # - baidu_verify_Pzk56fVe1P.html
  # - baidu_verify_rY1gqenItb.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: false
future: false
# highlight:
#   enable: true
#   line_number: false
#   auto_detect: true
#   tab_replace: ''
#   wrap: true
#   hljs: true

highlight:
  enable: true
  line_number: true # 改为false
  auto_detect: true
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 4
  order_by: -updated

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: true

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude: 
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly
# Extensions
feed:
    limit: 20
    order_by: "-updated"
    tag_dir: "tag"
    category_dir: "category"
    rss:
        enable: true
        template: 
        output: "rss.xml"
    atom:
        enable: true
        template: 
        output: "atom.xml"
    jsonFeed:
        enable: true
        template: 
        output: "feed.json"

# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
        
aplayer:
  asset_inject: false
  meting: true

# hexo-tag-dplayer:
#   cdn:
#     - https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js
#     - https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.css
#   default: 
#     api: https://api.prprpr.me/dplayer/
#     loop: yes
#     screenshot: yes
#     autoplay: false
#     hotkey: true
#     playbackSpeed: [0.5, 0.75, 1, 1.25, 1.5, 2]
#     theme: #FADFA3
    
    

baidu_url_submit:
  count: 50               # 提交最新的多少个链接
  host: ccknbc.github.io  # 在百度站长平台中添加的域名
  token: 9TyGjimf05CnCOTl   # 秘钥
  path: baidu_urls.txt   # 文本文档的地址， 新链接会保存在此文本文档里

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: 'git'
  repo: 
   a: git@github.com:CCKNBC/ccknbc.github.io.git
   b: git@e.coding.net:ccknbc/blog.git
   c: git@gitee.com:ccknbc/ccknbc.git
   #d: git@gitee.com:ccknbcgroup/ccknbc.git
  branch: master
- type: baidu_url_submitter # 这是新加的主动推送
  
admin:
 deployCommand: 'hexo-pubish.bat'


