title: CC的部落格
subtitle: CC康纳百川
description: CC的部落格，CC康纳百川的小窝，与你分享二三事
keywords: CC的部落格,CC康纳百川,ccknbc,blog
author: CC康纳百川
email: blog@ccknbc.cc
language: zh-CN
timezone: Asia/Shanghai

url: https://blog.ccknbc.cc
root: /
permalink: posts/:translate_title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: true
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  auto_detect: false
  line_number: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  quotes: '“”‘’'
  modifyAnchors: 0
  anchorAlias: true
  autolink: true
  mangle: true
  sanitizeUrl: false
  headerIds: true
  lazyload: true
  prependRoot: false
  postAsset: false
  external_link:
    enable: true
    exclude: [www.ccknbc.cc,ccknbc.cc]
    nofollow: true
  disableNunjucks: false
  descriptionLists: true
stylus:
  compress: true
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .
  plugins: 'nib'

index_generator:
  path: ''
  per_page: 10
  order_by: -date

default_category:
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

per_page: 0
pagination_dir: page

include:
exclude:
ignore:

theme: butterfly

feed:
  enable: true
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss.xml
  limit: 5
  hub:
  content: true
  content_limit: false
  content_limit_delim: ' '
  order_by: -updated
  icon: https://cdn.jsdelivr.net/gh/ccknbc-backup/cdn/logo/logo.png
  autodiscovery: true
  template:
    - ./source/_data/atom.xml
    - ./source/_data/rss.xml

sitemap:
  path: sitemap.xml
  template:
  rel: true
  tags: false
  categories: false

translate_title:
  translate_way:  google
  youdao_api_key: ''
  youdao_keyfrom: xxxx-blog
  is_need_proxy: false
  proxy_url: http://localhost:8080
  baidu_appid: ''
  baidu_appkey: ''
  rewrite: false

use_webp: false

plugins:
  - hexo-algoliasearch

algolia:
  appId: "947RX7HP3E"
  applicationID: "947RX7HP3E"
  apiKey: "9114b3fa2a3307b2cc8eec7e3ae5a8ea"
  chunkSize: 5000
  indexName: "ccknbc-blog"
  fields:
    - path
    - title
    - content:strip

nofollow:
  enable: true
  field: site
  exclude:
    - 'ccknbc.com'
    - 'www.ccknbc.com'

archive_generator:
  enabled: true
  per_page: 0
  yearly: false
  monthly: false
  daily: false
  order_by: -date

category_generator:
  per_page: 0
  order_by: -date

tag_generator:
  per_page: 0
  order_by: -date

webPushNotification:
  webpushrKey: "19e7fc04388c7dd68a5926d7326f3bea"
  webpushrAuthToken: "16778"
  trackingCode: "BB9Y-w9p3u0CKA7UP9nupB6I-_NqE2MuODmKJjyC4W2YflX06Ff_hEhrNJfonrut5l6gCa28gC83q2OII7Qv-oA"

memorial_day:
  enable: false
  day: 2021-05-22

douban:
  user: CCKNBC
  builtin: true
  book:
    title: 'This is my book title'
    quote: 'This is my book quote'
    meta: true
    comments: true
    top_img: false
    aside: false
    path: books
  movie:
    title: '我看过的影视'
    quote: '我看过的影视'
    meta: true
    comments: true
    top_img: false
    aside: false
    path: movies
  # game:
  #   title: 'This is my game title'
  #   quote: 'This is my game quote'
  #   meta: true
  #   comments: true
  #   top_img: false
  #   aside: false
  #   path: games
  timeout: 10000

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  CDN:
    anima: https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css #动画标签anima的依赖
    jquery: false #https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #issues标签依赖
    issues: false #https://cdn.jsdelivr.net/npm/hexo-theme-volantis@latest/source/js/issues.min.js #issues标签依赖
    iconfont: false #//at.alicdn.com/t/font_2032782_8d5kxvn09md.js #参看https://akilar.top/posts/d2ebecef/

wowjs:
  enable: true #控制动画开关。true是打开，false是关闭
  priority: 10 #过滤器优先级
  mobile: false #移动端是否启用，默认移动端禁用
  animateitem:
    - class: recent-post-item #必填项，需要添加动画的元素的class
      style: animate__zoomIn #必填项，需要添加的动画
      duration: 2s #选填项，动画持续时间，单位可以是ms也可以是s。例如3s，700ms。
      delay: 1s #选填项，动画开始的延迟时间，单位可以是ms也可以是s。例如3s，700ms。
      offset: 100 #选填项，开始动画的距离（相对浏览器底部）
      iteration: 2 #选填项，动画重复的次数
    - class: card-widget
      style: animate__zoomIn