name: Update Gitee Pages

on: 
  # push:
  #   branches: 
  #     - master
  workflow_dispatch:
    inputs:
      name:
        description: '手动触发'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: ccknbc
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ccknbc/blog