name: Deploy

on: 
  push:
    branches:
      - master

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        
    - name: Install Dependencies
      run: |
        rm -rf ./node_modules
        npm config set registry https://registry.npm.taobao.org/
        npm install hexo-cli -g
        npm install

    - name: Generate
      run: |
        hexo clean
        hexo generate
    
    - name: Deploy
      run: |
        hexo deploy