name: Deploy

on: 
  push:
    branches:
      - master

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        
    - name: Install Dependencies
      run: |
        npm config set registry http://r.cnpmjs.org/
        npm install hexo-cli gulp-cli -g
        npm install

    - name: Generate
      run: |
        hexo clean
        hexo generate
        gulp
    
    - name: Deploy
      run: |
        git config --global user.name "CCKNBC"
        git config --global user.email "zekangsun@outlook.com"
        hexo deploy

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: ccknbc
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ccknbc/ccknbc