name: Deploy Hexo Public To Pages

on: 
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@main
      with:
        node-version: "15.x"

    - name: Catch
      uses: actions/cache@main
      id: cache-dependencies
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        npm install

    # - name: Generate
    #   run: |
    #     npm run github

    - name: Generate
      run: |
        git clone -b json https://github.com/ccknbc-actions/blog-butterfly.git json
        mv -f ./json/yuque.json ./
        npm run github-yuque
        mv -f yuque.json ./json/

    - name: Deploy Json To Branch Json
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: json
        publish_dir: ./json
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        full_commit_message: ${{ github.event.head_commit.message }}
    
    - name: Deploy Markdown Posts To Branch Posts
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: posts
        publish_dir: ./source/_posts
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        full_commit_message: ${{ github.event.head_commit.message }}
    
    - name: Deploy Hexo Public To Pages
      run: |
        cd ./public
        git config --global http.postBuffer 157286400
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git init
        git add -A
        git branch -m master
        git commit -m "${{ github.event.head_commit.message }} $(date +"%Z %Y-%m-%d %A %H:%M:%S") Updated By Github Actions"
        git push --force --quiet "https://ccknbc:${{ secrets.GT_TOKEN }}@gitee.com/ccknbc/ccknbc.git" master:master
        git push --force --quiet "https://ccknbc:${{ secrets.GH_TOKEN }}@github.com/CCKNBC/ccknbc.github.io.git" master:master
        git push --force --quiet "https://${{ secrets.CD_USER }}:${{ secrets.CD_TOKEN }}@e.coding.net/ccknbc/blog/butterfly.git" master:master

    - name: Update Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
          gitee-username: ccknbc
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: ccknbc/ccknbc
    
    - name: Purge JsDelivr CDN
      run: |
        curl https://purge.jsdelivr.net/gh/CCKNBC/ccknbc.github.io/
        curl https://purge.jsdelivr.net/gh/CCKNBC/ccknbc.github.io/css/index.css
        curl https://purge.jsdelivr.net/gh/CCKNBC/ccknbc.github.io/js/main.js
        curl https://purge.jsdelivr.net/gh/CCKNBC/ccknbc.github.io/js/utils.js

    - name: Sync RSS
      run: |
        curl 'https://kkapi.vercel.app/api/github?type=dispatch&owner=ccknbc-actions&repo=home&token=${{ secrets.GH_TOKEN }}&runit_text=RSS'
        curl -X POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=master https://gitlab.com/api/v4/projects/22130436/trigger/pipeline

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1

    - name: Telegram Notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TG_BOT_TOKEN }}
        chatId: ${{ secrets.TG_CHAT_ID }}
        jobStatus: ${{ job.status }}
        skipSuccess: false
